name: XLogDecoder
options:
  bundleIdPrefix: com.yuxilong
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  XLogDecoder:
    type: application
    platform: macOS

    sources:
      - XLogDecoderApp.swift
      - ContentView.swift
      - Models
      - ViewModels
      - Views
      - Services
      - Utilities
      - path: Assets.xcassets
        buildPhase: resources

    settings:
      PRODUCT_NAME: XLogDecoder
      PRODUCT_BUNDLE_IDENTIFIER: com.yuxilong.XLogDecoder
      INFOPLIST_FILE: Info.plist
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      SWIFT_VERSION: "5.9"
      ENABLE_PREVIEWS: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "-"
      COMBINE_HIDPI_IMAGES: YES
      GENERATE_INFOPLIST_FILE: NO

    scheme:
      testTargets: []
      gatherCoverageData: false

    dependencies: []
